classdef CableJointAnimationTest < matlab.unittest.TestCase
    %CableJointAnimationTest 绳驱关节动画行为测试。

    methods (TestClassSetup)
        function addProjectRootToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(projectRoot));
        end
    end

    methods (TestMethodSetup)
        function hideFigures(testCase)
            clear animate_cable_joint
            existingFigures = findall(groot, Type="figure");
            originalVisibility = get(groot, "defaultFigureVisible");
            set(groot, "defaultFigureVisible", "off");
            testCase.addTeardown( ...
                @() set(groot, "defaultFigureVisible", originalVisibility));
            testCase.addTeardown( ...
                @() CableJointAnimationTest.closeNewFigures(existingFigures));
        end
    end

    methods (Test)
        function testRejectsMismatchedTrajectoryLength(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            testCase.verifyError(@() animate_cable_joint( ...
                [0, 0.1], zeros(3, 3), fixedPoints, movingPoints, ...
                160, 80, RealtimePlayback=false, Visible="off"), ...
                "CableJointAnimation:TrajectorySize");
        end

        function testCreatesTaggedStaticGeometry(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            figureHandle = animate_cable_joint( ...
                0, [0; 0; 39], fixedPoints, movingPoints, ...
                160, 80, PlatformThickness=1, ActuatorRadius=5, ...
                RealtimePlayback=false, Visible="off");

            axesHandle = findobj(figureHandle, Tag="CableJointAxes");
            fixedPlatform = findobj(figureHandle, Tag="FixedPlatform");
            fixedPlatformSurfaces = findobj(fixedPlatform, Type="surface");
            actuator = findobj(figureHandle, Tag="CenterActuator");

            testCase.assertNumElements(axesHandle, 1);
            testCase.assertNumElements(fixedPlatform, 1);
            testCase.assertNumElements(actuator, 1);
            testCase.assertNumElements(fixedPlatformSurfaces, 3);
            testCase.verifyEqual(axesHandle.DataAspectRatio, [1, 1, 1]);
            radialDistance = hypot(actuator.XData, actuator.YData);
            testCase.verifyEqual( ...
                radialDistance, 5 * ones(size(radialDistance)), ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                [min(arrayfun(@(surfaceHandle) ...
                    min(surfaceHandle.ZData, [], "all"), ...
                    fixedPlatformSurfaces)), ...
                 max(arrayfun(@(surfaceHandle) ...
                    max(surfaceHandle.ZData, [], "all"), ...
                    fixedPlatformSurfaces))], ...
                [-0.5, 0.5], AbsTol=1e-10);
        end

        function testAxesCoverFullyTiltedMovingPlatform(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            height = 39;
            movingPlatformRadius = 80;
            halfThickness = 0.5;

            figureHandle = animate_cable_joint( ...
                0, [pi / 2; 0; height], fixedPoints, movingPoints, ...
                160, movingPlatformRadius, PlatformThickness=1, ...
                RealtimePlayback=false, Visible="off");

            axesHandle = findobj(figureHandle, Tag="CableJointAxes");
            theoreticalLimits = [ ...
                height - movingPlatformRadius - halfThickness, ...
                height + movingPlatformRadius + halfThickness];

            testCase.assertNumElements(axesHandle, 1);
            testCase.verifyLessThanOrEqual( ...
                axesHandle.ZLim(1), theoreticalLimits(1));
            testCase.verifyGreaterThanOrEqual( ...
                axesHandle.ZLim(2), theoreticalLimits(2));
        end

        function testRejectsInfinitePlatformRadius(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            testCase.verifyError(@() animate_cable_joint( ...
                0, [0; 0; 39], fixedPoints, movingPoints, ...
                Inf, 80, RealtimePlayback=false, Visible="off"), ...
                "MATLAB:validators:mustBeFinite");
        end

        function testFinalFrameMatchesPoseAndCableEndpoints(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = [0, 0.01];
            alpha = deg2rad(4);
            beta = deg2rad(-3);
            finalHeight = 45;
            movingRadius = 80;
            halfThickness = 0.5;
            position = [0; 0; finalHeight];
            rotation = rpy_rotation(alpha, beta, 0);
            qTrajectory = [0, alpha; 0, beta; 39, finalHeight];
            expectedMovingNodes = position + rotation * movingPoints;

            figureHandle = animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, movingRadius, PlatformThickness=1, ActuatorRadius=5, ...
                RealtimePlayback=false, Visible="off");

            movingNodes = findobj(figureHandle, Tag="MovingNodes");
            fixedNodes = findobj(figureHandle, Tag="FixedNodes");
            movingPlatform = findobj(figureHandle, Tag="MovingPlatform");
            movingPlatformTop = findobj( ...
                movingPlatform, Type="surface", Tag="Top");
            movingPlatformBottom = findobj( ...
                movingPlatform, Type="surface", Tag="Bottom");
            movingPlatformSide = findobj( ...
                movingPlatform, Type="surface", Tag="Side");
            actuator = findobj(figureHandle, Tag="CenterActuator");
            poseStatus = findobj(figureHandle, Tag="PoseStatus");

            testCase.assertNumElements(movingNodes, 1);
            testCase.assertNumElements(fixedNodes, 1);
            testCase.assertNumElements(movingPlatform, 1);
            testCase.assertNumElements(movingPlatformTop, 1);
            testCase.assertNumElements(movingPlatformBottom, 1);
            testCase.assertNumElements(movingPlatformSide, 1);
            testCase.assertNumElements(actuator, 1);
            testCase.assertNumElements(poseStatus, 1);
            testCase.assertNumElements( ...
                findobj(movingPlatform, Type="surface"), 3);

            segmentPointCount = size(movingPlatformTop.XData, 2);
            theta = linspace(0, 2 * pi, segmentPointCount);
            radialCoordinates = [ ...
                zeros(1, segmentPointCount); ...
                movingRadius * ones(1, segmentPointCount)];
            faceX = radialCoordinates .* cos(theta);
            faceY = radialCoordinates .* sin(theta);
            topZ = halfThickness * ones(size(faceX));
            bottomZ = -halfThickness * ones(size(faceX));
            sideX = movingRadius * [cos(theta); cos(theta)];
            sideY = movingRadius * [sin(theta); sin(theta)];
            sideZ = repmat( ...
                [-halfThickness; halfThickness], 1, segmentPointCount);

            expectedTopWorld = position + rotation * ...
                [faceX(:)'; faceY(:)'; topZ(:)'];
            expectedBottomWorld = position + rotation * ...
                [faceX(:)'; faceY(:)'; bottomZ(:)'];
            expectedSideWorld = position + rotation * ...
                [sideX(:)'; sideY(:)'; sideZ(:)'];

            testCase.verifyEqual(movingPlatformTop.XData, ...
                reshape(expectedTopWorld(1, :), ...
                    size(movingPlatformTop.XData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformTop.YData, ...
                reshape(expectedTopWorld(2, :), ...
                    size(movingPlatformTop.YData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformTop.ZData, ...
                reshape(expectedTopWorld(3, :), ...
                    size(movingPlatformTop.ZData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformBottom.XData, ...
                reshape(expectedBottomWorld(1, :), ...
                    size(movingPlatformBottom.XData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformBottom.YData, ...
                reshape(expectedBottomWorld(2, :), ...
                    size(movingPlatformBottom.YData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformBottom.ZData, ...
                reshape(expectedBottomWorld(3, :), ...
                    size(movingPlatformBottom.ZData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformSide.XData, ...
                reshape(expectedSideWorld(1, :), ...
                    size(movingPlatformSide.XData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformSide.YData, ...
                reshape(expectedSideWorld(2, :), ...
                    size(movingPlatformSide.YData)), AbsTol=1e-10);
            testCase.verifyEqual(movingPlatformSide.ZData, ...
                reshape(expectedSideWorld(3, :), ...
                    size(movingPlatformSide.ZData)), AbsTol=1e-10);

            testCase.verifyEqual( ...
                [movingNodes.XData; movingNodes.YData; movingNodes.ZData], ...
                expectedMovingNodes, AbsTol=1e-10);
            testCase.verifyEqual( ...
                [fixedNodes.XData; fixedNodes.YData; fixedNodes.ZData], ...
                fixedPoints, AbsTol=1e-10);

            for cableIndex = 1:3
                cable = findobj( ...
                    figureHandle, Tag="Cable" + cableIndex);
                testCase.assertNumElements(cable, 1);
                testCase.verifyEqual( ...
                    [cable.XData(1); cable.YData(1); cable.ZData(1)], ...
                    fixedPoints(:, cableIndex), AbsTol=1e-10);
                testCase.verifyEqual( ...
                    [cable.XData(2); cable.YData(2); cable.ZData(2)], ...
                    expectedMovingNodes(:, cableIndex), AbsTol=1e-10);
            end

            testCase.verifyEqual( ...
                [min(actuator.ZData, [], "all"), ...
                 max(actuator.ZData, [], "all")], ...
                [0, finalHeight], AbsTol=1e-10);
            testCase.verifyThat(poseStatus.String, ...
                matlab.unittest.constraints.ContainsSubstring("h = 45"));
        end

        function testDoesNotCreateVideoWhenExportDisabled(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            videoFile = string(tempname) + ".mp4";
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteFileIfPresent(videoFile));

            animate_cable_joint( ...
                [0, 0.1], [0, 0; 0, 0; 39, 40], ...
                fixedPoints, movingPoints, 160, 80, ...
                ExportVideo=false, VideoFile=videoFile, ...
                RealtimePlayback=false, Visible="off");

            testCase.verifyFalse(isfile(videoFile));
        end

        function testExportsNonemptyMp4WithTrajectoryDuration(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = [0, 0.1];
            qTrajectory = [0, deg2rad(8); 0, deg2rad(-6); 39, 55];
            videoFile = string(tempname) + ".mp4";
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteFileIfPresent(videoFile));
            aviFilesBefore = CableJointAnimationTest.listTemporaryAviFiles();

            animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, 80, ExportVideo=true, VideoFile=videoFile, ...
                VideoFrameRate=30, RealtimePlayback=false, Visible="on");

            videoInfo = dir(videoFile);
            testCase.assertTrue(isfile(videoFile));
            testCase.verifyGreaterThan(videoInfo.bytes, 0);
            metadata = CableJointAnimationTest.probeVideo(videoFile);
            testCase.verifyEqual(metadata.FrameRate, 30, AbsTol=0.1);
            testCase.verifyEqual(metadata.Duration, 0.1, AbsTol=0.04);
            testCase.verifyEqual(metadata.FrameCount, 3);
            frameHashes = ...
                CableJointAnimationTest.readVideoFrameHashes(videoFile);
            testCase.verifyNumElements(frameHashes, 3);
            testCase.verifyNotEqual(frameHashes(1), frameHashes(end));
            testCase.verifyEqual( ...
                CableJointAnimationTest.listTemporaryAviFiles(), ...
                aviFilesBefore);
        end

        function testRealtimePlaybackTracksSimulationTime(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = 0:0.05:0.1;
            qTrajectory = [zeros(2, numel(time)); 39, 40, 41];

            warmupFigure = animate_cable_joint( ...
                0, [0; 0; 39], fixedPoints, movingPoints, ...
                160, 80, ExportVideo=false, ...
                RealtimePlayback=false, Visible="off");
            delete(warmupFigure);

            playbackTimer = tic;
            animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, 80, ExportVideo=false, ...
                RealtimePlayback=true, Visible="off");
            elapsed = toc(playbackTimer);

            testCase.verifyGreaterThanOrEqual(elapsed, 0.08);
            testCase.verifyLessThan(elapsed, 1);
        end

        function testRealtimePlaybackWaitsBeforeRenderingNextFrame(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = [0, 0.15, 0.30];
            qTrajectory = [zeros(2, numel(time)); 39, 45, 51];
            appdataKey = "CableJointObservedPose_" + ...
                replace(string(java.util.UUID.randomUUID), "-", "_");
            testCase.addTeardown( ...
                @() CableJointAnimationTest.removeRootAppdata(appdataKey));
            observationTimer = timer( ...
                StartDelay=0.07, ...
                TimerFcn=@(timerHandle, ~) ...
                    CableJointAnimationTest.capturePoseStatus( ...
                        timerHandle, appdataKey));
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteTimer(observationTimer));
            originalTextCreateFcn = get(groot, "defaultTextCreateFcn");
            set(groot, "defaultTextCreateFcn", ...
                @(textHandle, ~) ...
                    CableJointAnimationTest.startPoseTimer( ...
                        textHandle, observationTimer));
            testCase.addTeardown(@() set( ...
                groot, "defaultTextCreateFcn", originalTextCreateFcn));

            animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, 80, ExportVideo=false, ...
                RealtimePlayback=true, Visible="on");

            if ~isappdata(groot, appdataKey) && ...
                    strcmp(observationTimer.Running, "on")
                wait(observationTimer);
            end
            testCase.assertTrue(isappdata(groot, appdataKey));
            observedStatus = getappdata(groot, appdataKey);
            testCase.verifyThat(observedStatus, ...
                matlab.unittest.constraints.ContainsSubstring("t = 0.000"));
        end

        function testReportsUnavailableMp4EncoderWithoutFfmpeg(testCase)
            testCase.assumeFalse( ...
                CableJointAnimationTest.hasNativeMpeg4Profile());
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            emptyPath = string(tempname);
            mkdir(emptyPath);
            testCase.addTeardown(@() rmdir(emptyPath, "s"));
            pathCleanup = CableJointAnimationTest.useTemporaryPath(emptyPath);
            videoFile = string(tempname) + ".mp4";
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteFileIfPresent(videoFile));

            testCase.verifyError(@() animate_cable_joint( ...
                [0, 0.1], [0, 0; 0, 0; 39, 40], ...
                fixedPoints, movingPoints, 160, 80, ...
                ExportVideo=true, VideoFile=videoFile, ...
                RealtimePlayback=false, Visible="on"), ...
                "CableJointAnimation:Mp4EncoderUnavailable");

            delete(pathCleanup);
            testCase.verifyFalse(isfile(videoFile));
        end

        function testCleansFallbackFilesWhenMp4EncodingFails(testCase)
            testCase.assumeFalse( ...
                CableJointAnimationTest.hasNativeMpeg4Profile());
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            fakeBin = string(tempname);
            mkdir(fakeBin);
            testCase.addTeardown(@() rmdir(fakeBin, "s"));
            CableJointAnimationTest.createFailingFfmpeg(fakeBin);
            pathCleanup = CableJointAnimationTest.useTemporaryPath(fakeBin);
            videoFile = string(tempname) + ".mp4";
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteFileIfPresent(videoFile));
            aviFilesBefore = CableJointAnimationTest.listTemporaryAviFiles();

            testCase.verifyError(@() animate_cable_joint( ...
                [0, 0.1], [0, 0; 0, 0; 39, 40], ...
                fixedPoints, movingPoints, 160, 80, ...
                ExportVideo=true, VideoFile=videoFile, ...
                VideoFrameRate=30, RealtimePlayback=false, Visible="on"), ...
                "CableJointAnimation:Mp4EncodingFailed");

            delete(pathCleanup);
            testCase.verifyFalse(isfile(videoFile));
            testCase.verifyEqual( ...
                CableJointAnimationTest.listTemporaryAviFiles(), ...
                aviFilesBefore);
        end

        function testClosingWindowStopsRealtimePlaybackSafely(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = 0:0.05:1;
            qTrajectory = [zeros(2, numel(time)); ...
                linspace(39, 45, numel(time))];
            windowName = "绳驱三自由度关节动画";
            closeTimer = timer( ...
                StartDelay=0.03, ...
                ExecutionMode="fixedSpacing", ...
                Period=0.03, ...
                TasksToExecute=100, ...
                TimerFcn=@(timerHandle, ~) ...
                    CableJointAnimationTest.closeFigureByName( ...
                        timerHandle, windowName));
            testCase.addTeardown( ...
                @() CableJointAnimationTest.deleteTimer(closeTimer));
            start(closeTimer);

            figureHandle = animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, 80, ExportVideo=false, ...
                RealtimePlayback=true, Visible="on");

            testCase.verifyFalse(isgraphics(figureHandle));
        end
    end

    methods (Static, Access=private)
        function closeNewFigures(existingFigures)
            currentFigures = findall(groot, Type="figure");
            newFigures = currentFigures(~ismember(currentFigures, existingFigures));
            delete(newFigures(isgraphics(newFigures)));
        end

        function [fixedPoints, movingPoints] = platformGeometry()
            fixedPoints = [ ...
                160, -80, -80;
                0, 80 * sqrt(3), -80 * sqrt(3);
                0, 0, 0];
            movingPoints = [ ...
                80, -40, -40;
                0, 40 * sqrt(3), -40 * sqrt(3);
                0, 0, 0];
        end

        function closeFigureByName(timerHandle, windowName)
            figureHandles = findall(groot, ...
                Type="figure", Name=windowName);
            if isempty(figureHandles)
                return;
            end
            delete(figureHandles(isgraphics(figureHandles)));
            stop(timerHandle);
        end

        function deleteTimer(timerHandle)
            if ~isvalid(timerHandle)
                return;
            end
            stop(timerHandle);
            delete(timerHandle);
        end

        function deleteFileIfPresent(filePath)
            if isfile(filePath)
                delete(filePath);
            end
        end

        function startPoseTimer(textHandle, timerHandle)
            if textHandle.Tag == "PoseStatus" && ...
                    strcmp(timerHandle.Running, "off")
                start(timerHandle);
            end
        end

        function capturePoseStatus(timerHandle, appdataKey)
            figureHandles = findall(groot, Type="figure", ...
                Name="绳驱三自由度关节动画");
            if isempty(figureHandles)
                return;
            end
            poseStatus = findobj(figureHandles(1), Tag="PoseStatus");
            if isempty(poseStatus)
                return;
            end
            setappdata(groot, appdataKey, string(poseStatus.String));
            stop(timerHandle);
        end

        function removeRootAppdata(appdataKey)
            if isappdata(groot, appdataKey)
                rmappdata(groot, appdataKey);
            end
        end

        function aviFiles = listTemporaryAviFiles()
            listing = dir(fullfile(tempdir, "*.avi"));
            aviFiles = sort(string({listing.name}));
        end

        function nativeProfile = hasNativeMpeg4Profile()
            profiles = VideoWriter.getProfiles;
            nativeProfile = any(string({profiles.Name}) == "MPEG-4");
        end

        function cleanup = useTemporaryPath(pathValue)
            originalPath = getenv("PATH");
            setenv("PATH", pathValue);
            cleanup = onCleanup(@() setenv("PATH", originalPath));
        end

        function createFailingFfmpeg(directory)
            scriptPath = fullfile(directory, "ffmpeg");
            fileId = fopen(scriptPath, "w");
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "#!/bin/sh\nexit 1\n");
            clear cleanup;
            [status, commandOutput] = system( ...
                "chmod +x " + CableJointAnimationTest.shellQuote(scriptPath));
            if status ~= 0
                error("CableJointAnimationTest:ChmodFailed", ...
                    "Failed to make fake ffmpeg executable: %s", ...
                    commandOutput);
            end
        end

        function quotedPath = shellQuote(filePath)
            quotedPath = "'" + replace(string(filePath), "'", "'""'""'") + "'";
        end

        function metadata = probeVideo(videoFile)
            command = "ffprobe -v error -select_streams v:0 " + ...
                "-show_entries stream=r_frame_rate,nb_frames:" + ...
                "format=duration -of json " + ...
                CableJointAnimationTest.shellQuote(videoFile);
            [status, commandOutput] = system(command);
            if status ~= 0
                error("CableJointAnimationTest:FfprobeFailed", ...
                    "ffprobe failed: %s", commandOutput);
            end

            probeResult = jsondecode(commandOutput);
            frameRateParts = split( ...
                string(probeResult.streams.r_frame_rate), "/");
            metadata.FrameRate = ...
                str2double(frameRateParts(1)) / str2double(frameRateParts(2));
            metadata.FrameCount = ...
                str2double(string(probeResult.streams.nb_frames));
            metadata.Duration = ...
                str2double(string(probeResult.format.duration));
        end

        function frameHashes = readVideoFrameHashes(videoFile)
            command = "ffmpeg -v error -i " + ...
                CableJointAnimationTest.shellQuote(videoFile) + ...
                " -map 0:v:0 -f framemd5 -";
            [status, commandOutput] = system(command);
            if status ~= 0
                error("CableJointAnimationTest:FrameHashFailed", ...
                    "ffmpeg frame hashing failed: %s", commandOutput);
            end

            hashTokens = regexp(commandOutput, ...
                "(?m)^[^#\r\n]*,\s*([0-9a-f]{32})\s*$", "tokens");
            frameHashes = string(cellfun( ...
                @(token) token{1}, hashTokens, UniformOutput=false));
        end

    end
end
