classdef CableJointAnimationTest < matlab.unittest.TestCase
    %CableJointAnimationTest 绳驱关节动画行为测试。

    methods (TestClassSetup)
        function addProjectRootToPath(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(projectRoot));
        end
    end

    methods (TestMethodSetup)
        function hideFigures(testCase)
            existingFigures = findall(groot, Type="figure");
            originalVisibility = get(groot, "defaultFigureVisible");
            set(groot, "defaultFigureVisible", "off");
            testCase.addTeardown( ...
                @() set(groot, "defaultFigureVisible", originalVisibility));
            testCase.addTeardown( ...
                @() CableJointAnimationTest.closeNewFigures(existingFigures));
        end
    end

    methods (Test)
        function testRejectsMismatchedTrajectoryLength(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            testCase.verifyError(@() animate_cable_joint( ...
                [0, 0.1], zeros(3, 3), fixedPoints, movingPoints, ...
                160, 80, RealtimePlayback=false, Visible="off"), ...
                "CableJointAnimation:TrajectorySize");
        end

        function testCreatesTaggedStaticGeometry(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            figureHandle = animate_cable_joint( ...
                0, [0; 0; 39], fixedPoints, movingPoints, ...
                160, 80, PlatformThickness=1, ActuatorRadius=5, ...
                RealtimePlayback=false, Visible="off");

            axesHandle = findobj(figureHandle, Tag="CableJointAxes");
            fixedPlatform = findobj(figureHandle, Tag="FixedPlatform");
            fixedPlatformSurfaces = findobj(fixedPlatform, Type="surface");
            actuator = findobj(figureHandle, Tag="CenterActuator");

            testCase.assertNumElements(axesHandle, 1);
            testCase.assertNumElements(fixedPlatform, 1);
            testCase.assertNumElements(actuator, 1);
            testCase.assertNumElements(fixedPlatformSurfaces, 3);
            testCase.verifyEqual(axesHandle.DataAspectRatio, [1, 1, 1]);
            radialDistance = hypot(actuator.XData, actuator.YData);
            testCase.verifyEqual( ...
                radialDistance, 5 * ones(size(radialDistance)), ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                [min(arrayfun(@(surfaceHandle) ...
                    min(surfaceHandle.ZData, [], "all"), ...
                    fixedPlatformSurfaces)), ...
                 max(arrayfun(@(surfaceHandle) ...
                    max(surfaceHandle.ZData, [], "all"), ...
                    fixedPlatformSurfaces))], ...
                [-0.5, 0.5], AbsTol=1e-10);
        end

        function testAxesCoverFullyTiltedMovingPlatform(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            height = 39;
            movingPlatformRadius = 80;
            halfThickness = 0.5;

            figureHandle = animate_cable_joint( ...
                0, [pi / 2; 0; height], fixedPoints, movingPoints, ...
                160, movingPlatformRadius, PlatformThickness=1, ...
                RealtimePlayback=false, Visible="off");

            axesHandle = findobj(figureHandle, Tag="CableJointAxes");
            theoreticalLimits = [ ...
                height - movingPlatformRadius - halfThickness, ...
                height + movingPlatformRadius + halfThickness];

            testCase.assertNumElements(axesHandle, 1);
            testCase.verifyLessThanOrEqual( ...
                axesHandle.ZLim(1), theoreticalLimits(1));
            testCase.verifyGreaterThanOrEqual( ...
                axesHandle.ZLim(2), theoreticalLimits(2));
        end

        function testRejectsInfinitePlatformRadius(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();

            testCase.verifyError(@() animate_cable_joint( ...
                0, [0; 0; 39], fixedPoints, movingPoints, ...
                Inf, 80, RealtimePlayback=false, Visible="off"), ...
                "MATLAB:validators:mustBeFinite");
        end

        function testFinalFrameMatchesPoseAndCableEndpoints(testCase)
            [fixedPoints, movingPoints] = ...
                CableJointAnimationTest.platformGeometry();
            time = [0, 0.01];
            alpha = deg2rad(4);
            beta = deg2rad(-3);
            finalHeight = 45;
            movingRadius = 80;
            halfThickness = 0.5;
            position = [0; 0; finalHeight];
            rotation = rpy_rotation(alpha, beta, 0);
            qTrajectory = [0, alpha; 0, beta; 39, finalHeight];
            expectedMovingNodes = position + rotation * movingPoints;
            expectedTopPoint = position + ...
                rotation * [movingRadius; 0; halfThickness];
            expectedBottomPoint = position + ...
                rotation * [movingRadius; 0; -halfThickness];

            figureHandle = animate_cable_joint( ...
                time, qTrajectory, fixedPoints, movingPoints, ...
                160, movingRadius, PlatformThickness=1, ActuatorRadius=5, ...
                RealtimePlayback=false, Visible="off");

            movingNodes = findobj(figureHandle, Tag="MovingNodes");
            fixedNodes = findobj(figureHandle, Tag="FixedNodes");
            movingPlatform = findobj(figureHandle, Tag="MovingPlatform");
            movingPlatformTop = findobj( ...
                movingPlatform, Type="surface", Tag="Top");
            movingPlatformBottom = findobj( ...
                movingPlatform, Type="surface", Tag="Bottom");
            actuator = findobj(figureHandle, Tag="CenterActuator");
            poseStatus = findobj(figureHandle, Tag="PoseStatus");

            testCase.assertNumElements(movingNodes, 1);
            testCase.assertNumElements(fixedNodes, 1);
            testCase.assertNumElements(movingPlatform, 1);
            testCase.assertNumElements(movingPlatformTop, 1);
            testCase.assertNumElements(movingPlatformBottom, 1);
            testCase.assertNumElements(actuator, 1);
            testCase.assertNumElements(poseStatus, 1);
            testCase.assertNumElements( ...
                findobj(movingPlatform, Type="surface"), 3);
            testCase.verifyEqual( ...
                [movingPlatformTop.XData(2, 1); ...
                 movingPlatformTop.YData(2, 1); ...
                 movingPlatformTop.ZData(2, 1)], ...
                expectedTopPoint, AbsTol=1e-10);
            testCase.verifyEqual( ...
                [movingPlatformBottom.XData(2, 1); ...
                 movingPlatformBottom.YData(2, 1); ...
                 movingPlatformBottom.ZData(2, 1)], ...
                expectedBottomPoint, AbsTol=1e-10);
            testCase.verifyEqual( ...
                [movingNodes.XData; movingNodes.YData; movingNodes.ZData], ...
                expectedMovingNodes, AbsTol=1e-10);
            testCase.verifyEqual( ...
                [fixedNodes.XData; fixedNodes.YData; fixedNodes.ZData], ...
                fixedPoints, AbsTol=1e-10);

            for cableIndex = 1:3
                cable = findobj( ...
                    figureHandle, Tag="Cable" + cableIndex);
                testCase.assertNumElements(cable, 1);
                testCase.verifyEqual( ...
                    [cable.XData(1); cable.YData(1); cable.ZData(1)], ...
                    fixedPoints(:, cableIndex), AbsTol=1e-10);
                testCase.verifyEqual( ...
                    [cable.XData(2); cable.YData(2); cable.ZData(2)], ...
                    expectedMovingNodes(:, cableIndex), AbsTol=1e-10);
            end

            testCase.verifyEqual( ...
                [min(actuator.ZData, [], "all"), ...
                 max(actuator.ZData, [], "all")], ...
                [0, finalHeight], AbsTol=1e-10);
            testCase.verifyThat(poseStatus.String, ...
                matlab.unittest.constraints.ContainsSubstring("h = 45"));
        end
    end

    methods (Static, Access=private)
        function closeNewFigures(existingFigures)
            currentFigures = findall(groot, Type="figure");
            newFigures = currentFigures(~ismember(currentFigures, existingFigures));
            delete(newFigures(isgraphics(newFigures)));
        end

        function [fixedPoints, movingPoints] = platformGeometry()
            fixedPoints = [ ...
                160, -80, -80;
                0, 80 * sqrt(3), -80 * sqrt(3);
                0, 0, 0];
            movingPoints = [ ...
                80, -40, -40;
                0, 40 * sqrt(3), -40 * sqrt(3);
                0, 0, 0];
        end
    end
end
