function result = analyze_workspace( ...
        fixedPoints, movingPoints, drumRadius, options)
%ANALYZE_WORKSPACE Sample actuator inputs and evaluate feasible poses.

    arguments
        fixedPoints
        movingPoints
        drumRadius
        options.ActuatorAngleLimitDeg = [-135, 135]
        options.LinearActuatorRange = [150, 160]
        options.SampleCount = 100000
        options.RandomSeed = 0
        options.ReferencePoseDeg = [0; 0; 100]
        options.PoseAngleLimitDeg = [-90, 90]
        options.InitialGuessDeg = [0, 30, -30, 0, 0; 0, 0, 0, 30, -30]
        options.ForwardTolerance = 1e-6
        options.MaxIterations = 30
        options.TargetLoad = [0; 0; 1.2]
        options.PreferredForce = [1; 1; 1; 20]
        options.MinCableTension = 0
        options.StaticResidualTolerance = 1e-8
    end

    validateConfiguration(fixedPoints, movingPoints, drumRadius, options);
    referenceRotation = rpy_rotation( ...
        deg2rad(options.ReferencePoseDeg(1)), ...
        deg2rad(options.ReferencePoseDeg(2)), 0);
    referenceCableLength = calc_cable_length( ...
        fixedPoints, movingPoints, [0; 0; options.ReferencePoseDeg(3)], ...
        referenceRotation);

    sampleCount = options.SampleCount;
    stream = RandStream("mt19937ar", Seed=options.RandomSeed);
    theta1Deg = options.ActuatorAngleLimitDeg(1) ...
        + diff(options.ActuatorAngleLimitDeg) * rand(stream, 1, sampleCount);
    theta2Deg = options.ActuatorAngleLimitDeg(1) ...
        + diff(options.ActuatorAngleLimitDeg) * rand(stream, 1, sampleCount);
    height = options.LinearActuatorRange(1) ...
        + diff(options.LinearActuatorRange) * rand(stream, 1, sampleCount);
    result = initializeResult(theta1Deg, theta2Deg, height, sampleCount);
    actuatorLimitRad = deg2rad(options.ActuatorAngleLimitDeg);

    for sampleIndex = 1:sampleCount
        solution = solve_forward_kinematics( ...
            fixedPoints, movingPoints, ...
            [result.actuatorCommand(1:2, sampleIndex); height(sampleIndex)], ...
            referenceCableLength, drumRadius, ...
            InitialGuessDeg=options.InitialGuessDeg, ...
            PoseAngleLimitDeg=options.PoseAngleLimitDeg, ...
            ForwardTolerance=options.ForwardTolerance, ...
            MaxIterations=options.MaxIterations);

        result.forwardConverged(sampleIndex) = solution.converged;
        result.forwardResidualNorm(sampleIndex) = solution.residualNorm;
        if ~solution.converged
            continue;
        end

        result.pose(:, sampleIndex) = ...
            [solution.alpha; solution.beta; height(sampleIndex)];
        result.cableLength(:, sampleIndex) = solution.cableLength;
        result.actuatorCommand(3, sampleIndex) = ...
            (solution.cableLength(3) - referenceCableLength(3)) / drumRadius;
        drumAngles = result.actuatorCommand(1:3, sampleIndex);
        result.withinActuatorLimits(sampleIndex) = ...
            all(drumAngles >= actuatorLimitRad(1)) ...
            && all(drumAngles <= actuatorLimitRad(2));
        if ~result.withinActuatorLimits(sampleIndex)
            continue;
        end

        rotation = rpy_rotation(solution.alpha, solution.beta, 0);
        staticMatrix = calc_static_matrix( ...
            fixedPoints, movingPoints, [0; 0; height(sampleIndex)], rotation);
        staticResult = solve_tension_distribution( ...
            staticMatrix, options.TargetLoad, ...
            PreferredForce=options.PreferredForce, ...
            MinCableTension=options.MinCableTension, ...
            ResidualTolerance=options.StaticResidualTolerance);
        result.force(:, sampleIndex) = staticResult.force;
        result.minCableTension(sampleIndex) = min(staticResult.force(1:3));
        result.staticResidualNorm(sampleIndex) = staticResult.residualNorm;
        result.isTensionFeasible(sampleIndex) = staticResult.isFeasible;
        result.isFeasible(sampleIndex) = staticResult.isFeasible;
    end

    result.config = struct( ...
        actuatorAngleLimitDeg=options.ActuatorAngleLimitDeg, ...
        linearActuatorRange=options.LinearActuatorRange, ...
        sampleCount=options.SampleCount, randomSeed=options.RandomSeed, ...
        referencePoseDeg=options.ReferencePoseDeg, ...
        referenceCableLength=referenceCableLength, ...
        poseAngleLimitDeg=options.PoseAngleLimitDeg, ...
        initialGuessDeg=options.InitialGuessDeg, ...
        forwardTolerance=options.ForwardTolerance, ...
        maxIterations=options.MaxIterations, targetLoad=options.TargetLoad, ...
        preferredForce=options.PreferredForce, ...
        minCableTension=options.MinCableTension, ...
        staticResidualTolerance=options.StaticResidualTolerance, ...
        drumRadius=drumRadius);
end

function result = initializeResult(theta1Deg, theta2Deg, height, sampleCount)
    result = struct;
    result.pose = NaN(3, sampleCount);
    result.pose(3, :) = height;
    result.actuatorCommand = NaN(4, sampleCount);
    result.actuatorCommand(1:2, :) = deg2rad([theta1Deg; theta2Deg]);
    result.actuatorCommand(4, :) = height;
    result.cableLength = NaN(3, sampleCount);
    result.force = NaN(4, sampleCount);
    result.minCableTension = NaN(1, sampleCount);
    result.forwardResidualNorm = Inf(1, sampleCount);
    result.staticResidualNorm = NaN(1, sampleCount);
    result.forwardConverged = false(1, sampleCount);
    result.withinActuatorLimits = false(1, sampleCount);
    result.isTensionFeasible = false(1, sampleCount);
    result.isFeasible = false(1, sampleCount);
end

function validateConfiguration(fixedPoints, movingPoints, drumRadius, options)
    isValid = isFiniteDoubleArray(fixedPoints, [3, 3]) ...
        && isFiniteDoubleArray(movingPoints, [3, 3]) ...
        && isFiniteScalar(drumRadius) && drumRadius > 0 ...
        && isIncreasingRange(options.ActuatorAngleLimitDeg) ...
        && isIncreasingRange(options.LinearActuatorRange) ...
        && isPositiveInteger(options.SampleCount) ...
        && isNonnegativeInteger(options.RandomSeed) ...
        && isFiniteDoubleArray(options.ReferencePoseDeg, [3, 1]) ...
        && isIncreasingRange(options.PoseAngleLimitDeg) ...
        && isFiniteScalar(options.ForwardTolerance) ...
        && options.ForwardTolerance > 0 ...
        && isPositiveInteger(options.MaxIterations) ...
        && isFiniteDoubleArray(options.TargetLoad, [3, 1]) ...
        && isFiniteDoubleArray(options.PreferredForce, [4, 1]) ...
        && isFiniteScalar(options.MinCableTension) ...
        && isFiniteScalar(options.StaticResidualTolerance) ...
        && options.StaticResidualTolerance >= 0;
    if ~isValid
        error("CableJointWorkspace:InvalidConfiguration", ...
            "工作空间分析配置无效。");
    end
    if options.ReferencePoseDeg(3) < options.LinearActuatorRange(1) ...
            || options.ReferencePoseDeg(3) > options.LinearActuatorRange(2)
        error("CableJointWorkspace:InvalidConfiguration", ...
            "参考姿态高度必须位于直线执行器范围内。");
    end
end

function tf = isIncreasingRange(value)
    tf = isFiniteDoubleArray(value, [1, 2]) && value(1) < value(2);
end

function tf = isFiniteDoubleArray(value, expectedSize)
    tf = isa(value, "double") && isreal(value) ...
        && isequal(size(value), expectedSize) && all(isfinite(value), "all");
end

function tf = isFiniteScalar(value)
    tf = isa(value, "double") && isreal(value) ...
        && isscalar(value) && isfinite(value);
end

function tf = isPositiveInteger(value)
    tf = isFiniteScalar(value) && value > 0 && value == fix(value);
end

function tf = isNonnegativeInteger(value)
    tf = isFiniteScalar(value) && value >= 0 && value == fix(value);
end
